### ISSUE TITLE
Incompatible types: Integer cannot be converted to String for cf.previous_versions

### ISSUE THREAD

**Issue by hyjorc1** [boalang/compiler#240]
**BOA CODE:**
idx := cf.previous_versions[0];

**ERROR**: 
./compile/boa/AstFalse.java:299: error: incompatible types: Integer cannot be converted to String ___idx = ___cf.getPreviousVersionsList().get((int)(0l));

**REASON**
https://github.com/boalang/compiler/blob/74acd4f3050286d45a3738d51b2829dd1d59dd50/src/java/boa/types/proto/ChangedFileProtoTuple.java#L70-L74

**SOULDE BE**
names.put("previous_names", counter++);
members.add(new BoaProtoList(**new BoaString()**));
		
names.put("previous_versions", counter++);
members.add(new BoaProtoList(**new BoaInt()**));

**Comment by hridesh** [comment]
Should this be fixed in the generation step of this file? In other word, should this schema be fixed, and a new proto tuple file generated?

**Comment by psybers** [comment]
This file is not generated (since we never merged my shadow branch in).

It is manually mirroring the proto - so we have to see if the proto is right or not first, and then update this (or not).

**Comment by hyjorc1** [comment]
I think this file is used to specify the returning data type when cf.previous_versions is invoked. In my own local branch, I have already swap those two types. And it works fine now. But I am not sure, it is same to do that.

**Comment by hridesh** [comment]
Thanks for clarifying. In that case, might be best to fix this bug. The proto looks correct, so we can fix this bug.

On Jan 12, 2019, at 2:33 PM, Robert Dyer <notifications@github.com<mailto:notifications@github.com>> wrote:


This file is not generated (since we never merged my shadow branch in).

It is manually mirroring the proto - so we have to see if the proto is right or not first, and then update this (or not).
