### ISSUE TITLE
Error in code generation when getting length of array named "values" or "keys"

### ISSUE THREAD

**Issue by nmtiwari** [boalang/compiler#87]
Name an array `values` and try quantifying over it leads to codegen errors.

````
o: output sum of int;

values: array of int;
keys: array of int;

o << len(values);
o << len(keys);
````

Code generation for the above generates: 

````
____local_aggregator_o = ____local_aggregator_o + (((long)Double.NaN(1000 * 1000)Double.NaN(1000 * 1000)(60 * 60 * 1000 * 1000)Double.POSITIVE_INFINITYtrue_inputDouble.POSITIVE_INFINITYMath.PI(60 * 1000 * 1000)(60 * 1000 * 1000)(60 * 60 * 1000 * 1000    )false.length));
____local_aggregator_o = ____local_aggregator_o + (((long)nanSECONDNaNSECHRinftrueinputInfPIMINMINUTEHOURfalse.length));
````

**Comment by psybers** [comment]
Similar problem when using the name `keys` - this is a problem with the StringTemplate library we use.  Somehow when we do a lookup on the identifier (to find special identifiers like true/false) we use a map in ST.  Then we do an indirect lookup like `idmap.(id)` so when we have either keys/values as the identifier it is just dumping a list of all keys or values in the id map.

**Comment by psybers** [comment]
"StringTemplate interprets Map objects to have two predefined properties: keys and values that yield a list of all keys and the list of all values, respectively. When applying a template to a map, StringTemplate iterates over the values so that <aMap> is a shorthand for <aMap.values>. Similarly <aMap.keys> walks over the keys." - from https://theantlrguy.atlassian.net/wiki/display/ST/Expressions
